// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpqcsegkwmaiywhwgkfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wcWNzZWdrd21haXl3aHdna2Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MDc5NTYsImV4cCI6MjA2MDI4Mzk1Nn0.M8pCA1wPLqFCCNOS1U1x3ZiXPlfT8HLX5H7iaUiXR5g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);